### PR TITLE
Hi I have added the support for item template

### PR DESCRIPTION
**Pull request by ashrafuzzaman**
Hi,
I have added the item template support so that you can customize the auto complete list that is rendered. I needed to add profile picture in the auto complete. So I did this modification.

### CODE REVIEW

**Comment by tcrosen** [comment]
Hi there, can you please include test case(s) for the new functionality?

**Comment by ashrafuzzaman** [comment]
Hi I have added test.

**Comment by tcrosen** [comment]
Hi Ashra, thanks for your proposed contribution however rather than bake in custom templating logic I'd like to add support for mature templating libraries (mustache.js, underscore.js, etc).  Those libraries are thoroughly tested and secure and offer more flexibility for users.

Hopefully your code at the very least offers you the functionality you required and maybe some other followers of this plugin as well.

**Comment by ashrafuzzaman** [comment]
You are right. But I am not sure for a simple purpose as this people will want to add additional library.

**Pull request closed without merging**
